### ISSUE TITLE
"Disconnected from server"

### ISSUE THREAD

**Issue by ObeyBeastJj23** [FunnyBuddys/NewTesseract#2]
#### Problem description

On attempting to connect to server it just tries to load saying "Syncing pack with server..." on the screen then finally after about 40 seconds or so it will just say "Disconnected from server" on screen and in the Console it dosent say a name but just this:
[/109.154.183.125:49814] logged out due to Login timeout

#### Steps to reproduce the issue

Run latest Master, join server, wait... Disconnected.

#### OS and versions

* Tesseract: Tesseract-1.3.0 Unity
* PHP: 7.0.3
* Server OS: -Unknown-
* Game version:  1.1.0 [Latest from Google Play]
* Server host: Web Host
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by FunnyBuddys** [comment]
View https://github.com/FunnyBuddys/NewTesseract/issues/1
