### ISSUE TITLE
yaml_parse error!

### ISSUE THREAD

**Issue by armagadon159753** [FunnyBuddys/NewTesseract#5]
![_20170605_100545](https://cloud.githubusercontent.com/assets/25569806/26775780/b6ad5e70-49d6-11e7-837e-d28ae5e949d6.JPG)

**Comment by FunnyBuddys** [comment]
Fixed in https://github.com/FunnyBuddys/NewTesseract/commit/1eabfc2f78da99075b794016909bc65cee19bbf6
